# Generated by Django 4.2.7 on 2023-12-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chat',
        ),
    ]
