# Generated by Django 4.2.7 on 2023-12-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0010_tbl_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_photo',
        ),
    ]
