# Generated by Django 4.2.7 on 2023-12-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0014_tbl_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_chat',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='tbl_chat',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='tbl_photo',
        ),
        migrations.DeleteModel(
            name='tbl_chat',
        ),
    ]
